package vista;

import controlador.ControladorAlerta;
import modelo.Alerta;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

public class VistaAlertas extends JFrame { // Extiende JFrame

    private ControladorAlerta controladorAlerta;
    private JTable tablaAlertas;
    private DefaultTableModel modeloTabla;

    // Constructor
    public VistaAlertas() {
        controladorAlerta = new ControladorAlerta(); // Inicializa el controlador
        inicializarVentana(); // Llama al método que configura la ventana
    }

    // Inicializa la ventana y sus componentes
    private void inicializarVentana() {
        setTitle("Gestión de Alertas");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // O DISPOSE_ON_CLOSE según lo desees
        setSize(800, 600);

        // Crear el modelo de la tabla y agregar las columnas
        modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("ID Alerta");
        modeloTabla.addColumn("Condición");
        modeloTabla.addColumn("Mensaje");
        modeloTabla.addColumn("Fecha");
        modeloTabla.addColumn("Hora");

        // Crear la tabla con el modelo
        tablaAlertas = new JTable(modeloTabla);
        JScrollPane scrollPane = new JScrollPane(tablaAlertas);
        getContentPane().add(scrollPane, BorderLayout.CENTER);

        // Crear el botón para cargar alertas
        JButton btnCargarAlertas = new JButton("Cargar Alertas");
        btnCargarAlertas.addActionListener(e -> cargarAlertas());
        getContentPane().add(btnCargarAlertas, BorderLayout.SOUTH);

        setLocationRelativeTo(null); // Centra la ventana
    }

    // Método para cargar las alertas en la tabla
    private void cargarAlertas() {
        List<Alerta> alertas = controladorAlerta.obtenerAlertas(); // Este método debe estar implementado en ControladorAlerta
        modeloTabla.setRowCount(0); // Limpiar la tabla antes de insertar nuevas filas

        // Agregar las alertas a la tabla
        for (Alerta alerta : alertas) {
            modeloTabla.addRow(new Object[]{
                    alerta.getIdAlerta(),
                    alerta.getIdCondicion(),
                    alerta.getMensaje(),
                    alerta.getFecha(),
                    alerta.getHora()
            });
        }
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAlertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAlertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAlertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAlertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAlertas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
